/*###################################################################
### This JavaFX document was generated by Inkscape
### http://www.inkscape.org
### Created: Fri Feb 07 13:06:50 2020
### Version: 0.92.4 (5da689c313, 2019-01-14)
#####################################################################
### NOTES:
### ============
### JavaFX information can be found at
### http://www.javafx.com/
###
### If you have any problems with this output, please see the
### Inkscape project at http://www.inkscape.org, or visit
### the #inkscape channel on irc.freenode.net . 
###
###################################################################*/


/*###################################################################
##   Exports in this file
##==========================
##    Shapes   : 2
##    Nodes    : 143
###################################################################*/


import javafx.scene.*;
import javafx.scene.shape.*;
import javafx.scene.transform.*;
import javafx.scene.paint.*;



public class Comet32 extends CustomNode {
    /** path path4 */
    function path4() : Path {
        Path {
            id: "path4"
            opacity: 1.00000000
            fill: Color.rgb(0x11, 0x13, 0x17, 1.00000000)
            stroke: Color.rgb(0x00, 0x00, 0x00, 1.00000000)
            strokeWidth: 1.00000000
            strokeLineCap: StrokeLineCap.BUTT
            strokeLineJoin: StrokeLineJoin.MITER
            strokeMiterLimit: 4.00000000
            elements: [
                MoveTo {
                    x: 257.40895344
                    y: -256.05366589
                },
                CubicCurveTo {
                    controlX1: 257.49547788
                    controlY1: -256.18160511
                    controlX2: 257.47635752
                    controlY2: -256.35248240
                    x: 257.36169977
                    y: -256.45698381
                },
                CubicCurveTo {
                    controlX1: 257.24704202
                    controlY1: -256.56342274
                    controlX2: 257.07199742
                    controlY2: -256.57517290
                    x: 256.94427087
                    y: -256.48435918
                },
                LineTo {
                    x: 250.59998254
                    y: -252.02529925
                },
                CubicCurveTo {
                    controlX1: 250.47824318
                    controlY1: -251.94036061
                    controlX2: 250.31131024
                    controlY2: -251.94617318
                    x: 250.19658811
                    y: -252.04092446
                },
                CubicCurveTo {
                    controlX1: 250.08186598
                    controlY1: -252.13567573
                    controlX2: 250.04768111
                    controlY2: -252.29386536
                    x: 250.11508519
                    y: -252.42474212
                },
                LineTo {
                    x: 250.81320347
                    y: -253.77826031
                },
                CubicCurveTo {
                    controlX1: 250.87957750
                    controlY1: -253.90619953
                    controlX2: 250.84841840
                    controlY2: -254.06245163
                    x: 250.73878216
                    y: -254.15720290
                },
                CubicCurveTo {
                    controlX1: 250.62811586
                    controlY1: -254.25289169
                    controlX2: 250.46517438
                    controlY2: -254.26464184
                    x: 250.34143929
                    y: -254.18651579
                },
                LineTo {
                    x: 230.32577517
                    y: -242.16185418
                },
                CubicCurveTo {
                    controlX1: 230.12259725
                    controlY1: -242.04854016
                    controlX2: 229.92038501
                    controlY2: -241.93135109
                    x: 229.72525439
                    y: -241.80247435
                },
                LineTo {
                    x: 229.70915981
                    y: -241.79272422
                },
                LineTo {
                    x: 229.71018987
                    y: -241.79172421
                },
                CubicCurveTo {
                    controlX1: 229.21930533
                    controlY1: -241.46553233
                    controlX2: 228.74953687
                    controlY2: -241.09640237
                    x: 228.31395329
                    y: -240.67352168
                },
                CubicCurveTo {
                    controlX1: 224.51260781
                    controlY1: -236.98403460
                    controlX2: 224.51260781
                    controlY2: -231.00151669
                    x: 228.31292324
                    y: -227.31296712
                },
                CubicCurveTo {
                    controlX1: 230.21407882
                    controlY1: -225.46819233
                    controlX2: 232.70474649
                    controlY2: -224.54536742
                    x: 235.19534978
                    y: -224.54536742
                },
                CubicCurveTo {
                    controlX1: 237.68595307
                    controlY1: -224.54536742
                    controlX2: 240.17559069
                    controlY2: -225.46825483
                    x: 242.07681065
                    y: -227.31296712
                },
                CubicCurveTo {
                    controlX1: 242.51239422
                    controlY1: -227.73584780
                    controlX2: 242.89158241
                    controlY2: -228.19091642
                    x: 243.22757276
                    y: -228.66748532
                },
                LineTo {
                    x: 243.22757276
                    y: -228.66648531
                },
                LineTo {
                    x: 243.23458999
                    y: -228.67723545
                },
                CubicCurveTo {
                    controlX1: 243.35330358
                    controlY1: -228.84617522
                    controlX2: 243.46094410
                    controlY2: -229.01999006
                    x: 243.56755456
                    y: -229.19480491
                },
                LineTo {
                    x: 255.69481682
                    y: -248.07493366
                },
                CubicCurveTo {
                    controlX1: 255.77226392
                    controlY1: -248.19018520
                    controlX2: 255.76524668
                    controlY2: -248.34056223
                    x: 255.67672652
                    y: -248.44700116
                },
                CubicCurveTo {
                    controlX1: 255.58820636
                    controlY1: -248.55537761
                    controlX2: 255.43929935
                    controlY2: -248.59544065
                    x: 255.30655130
                    y: -248.54662750
                },
                LineTo {
                    x: 252.29177989
                    y: -247.44892524
                },
                CubicCurveTo {
                    controlX1: 252.15896745
                    controlY1: -247.40204961
                    controlX2: 252.01012482
                    controlY2: -247.44111264
                    x: 251.92160466
                    y: -247.54855158
                },
                CubicCurveTo {
                    controlX1: 251.83308450
                    controlY1: -247.65599053
                    controlX2: 251.82606726
                    controlY2: -247.80636755
                    x: 251.90448003
                    y: -247.92061908
                },
                LineTo {
                    x: 257.40895344
                    y: -256.05366589
                },
                ClosePath {},
                MoveTo {
                    x: 235.19541416
                    y: -227.49959463
                },
                CubicCurveTo {
                    controlX1: 233.40788628
                    controlY1: -227.49959463
                    controlX2: 231.72806330
                    controlY2: -228.17441620
                    x: 230.46463916
                    y: -229.40199519
                },
                CubicCurveTo {
                    controlX1: 227.85731801
                    controlY1: -231.93327921
                    controlX2: 227.85731801
                    controlY2: -236.05245958
                    x: 230.46463916
                    y: -238.58474361
                },
                CubicCurveTo {
                    controlX1: 230.90324852
                    controlY1: -239.00956182
                    controlX2: 231.39310301
                    controlY2: -239.36406658
                    x: 231.91817242
                    y: -239.65119544
                },
                CubicCurveTo {
                    controlX1: 232.39495811
                    controlY1: -239.91194895
                    controlX2: 232.90296728
                    controlY2: -240.11313915
                    x: 233.43106247
                    y: -240.25376604
                },
                CubicCurveTo {
                    controlX1: 233.48037625
                    controlY1: -240.26645371
                    controlX2: 233.53065570
                    controlY2: -240.27720386
                    x: 233.58196521
                    y: -240.28989153
                },
                CubicCurveTo {
                    controlX1: 233.78617317
                    controlY1: -240.33970470
                    controlX2: 233.99437260
                    controlY2: -240.37876772
                    x: 234.20463212
                    y: -240.40901813
                },
                CubicCurveTo {
                    controlX1: 234.27100615
                    controlY1: -240.41876826
                    controlX2: 234.33641450
                    controlY2: -240.42951840
                    x: 234.40278853
                    y: -240.43733101
                },
                CubicCurveTo {
                    controlX1: 234.66332751
                    controlY1: -240.46758141
                    controlX2: 234.92785795
                    controlY2: -240.48714418
                    x: 235.19547854
                    y: -240.48714418
                },
                CubicCurveTo {
                    controlX1: 236.98197636
                    controlY1: -240.48714418
                    controlX2: 238.66083367
                    controlY2: -239.81132259
                    x: 239.92425781
                    y: -238.58474361
                },
                CubicCurveTo {
                    controlX1: 240.07516054
                    controlY1: -238.43924165
                    controlX2: 240.21499021
                    controlY2: -238.28592709
                    x: 240.34773827
                    y: -238.12967499
                },
                CubicCurveTo {
                    controlX1: 240.39203054
                    controlY1: -238.07886181
                    controlX2: 240.43123692
                    controlY2: -238.02517359
                    x: 240.47250341
                    y: -237.97342289
                },
                CubicCurveTo {
                    controlX1: 240.55902785
                    controlY1: -237.86504644
                    controlX2: 240.64252650
                    controlY2: -237.75660748
                    x: 240.72093927
                    y: -237.64529348
                },
                CubicCurveTo {
                    controlX1: 240.76619722
                    controlY1: -237.58085512
                    controlX2: 240.80842938
                    controlY2: -237.51635425
                    x: 240.85072592
                    y: -237.45097837
                },
                CubicCurveTo {
                    controlX1: 240.91813000
                    controlY1: -237.34747698
                    controlX2: 240.98250830
                    controlY2: -237.24197556
                    x: 241.04386082
                    y: -237.13453662
                },
                CubicCurveTo {
                    controlX1: 241.08306721
                    controlY1: -237.06522319
                    controlX2: 241.12233797
                    controlY2: -236.99490974
                    x: 241.15954863
                    y: -236.92459630
                },
                CubicCurveTo {
                    controlX1: 241.21484959
                    controlY1: -236.81715735
                    controlX2: 241.26615909
                    controlY2: -236.70684337
                    x: 241.31547287
                    y: -236.59746690
                },
                CubicCurveTo {
                    controlX1: 241.34766202
                    controlY1: -236.52615344
                    controlX2: 241.38184690
                    controlY2: -236.45584000
                    x: 241.41101027
                    y: -236.38358903
                },
                CubicCurveTo {
                    controlX1: 241.46334983
                    controlY1: -236.25464979
                    controlX2: 241.50860777
                    controlY2: -236.12283552
                    x: 241.55186999
                    y: -235.99195876
                },
                CubicCurveTo {
                    controlX1: 241.59410215
                    controlY1: -235.86501956
                    controlX2: 241.63034714
                    controlY2: -235.73801785
                    x: 241.66453201
                    y: -235.60914112
                },
                CubicCurveTo {
                    controlX1: 241.68970393
                    controlY1: -235.51145230
                    controlX2: 241.71687157
                    controlY2: -235.41482601
                    x: 241.73798765
                    y: -235.31613718
                },
                CubicCurveTo {
                    controlX1: 241.76013379
                    controlY1: -235.20969825
                    controlX2: 241.77719404
                    controlY2: -235.10125929
                    x: 241.79431867
                    y: -234.99388285
                },
                CubicCurveTo {
                    controlX1: 241.80642179
                    controlY1: -234.91769432
                    controlX2: 241.81846053
                    controlY2: -234.84150580
                    x: 241.82753787
                    y: -234.76537978
                },
                CubicCurveTo {
                    controlX1: 241.84163672
                    controlY1: -234.64819070
                    controlX2: 241.85270978
                    controlY2: -234.53100163
                    x: 241.85972702
                    y: -234.41381255
                },
                CubicCurveTo {
                    controlX1: 241.86378285
                    controlY1: -234.35031170
                    controlX2: 241.86674425
                    controlY2: -234.28587333
                    x: 241.86977003
                    y: -234.22237248
                },
                CubicCurveTo {
                    controlX1: 241.87382587
                    controlY1: -234.09443326
                    controlX2: 241.87678727
                    controlY2: -233.96649404
                    x: 241.87279581
                    y: -233.83855482
                },
                CubicCurveTo {
                    controlX1: 241.87176576
                    controlY1: -233.79755427
                    controlX2: 241.86873998
                    controlY2: -233.75555371
                    x: 241.86674425
                    y: -233.71455315
                },
                CubicCurveTo {
                    controlX1: 241.83758088
                    controlY1: -233.06416941
                    controlX2: 241.70978996
                    controlY2: -232.41666071
                    x: 241.48047445
                    y: -231.79652738
                },
                CubicCurveTo {
                    controlX1: 241.47641862
                    controlY1: -231.78283969
                    controlX2: 241.47139711
                    controlY2: -231.76915201
                    x: 241.46637561
                    y: -231.75646434
                },
                CubicCurveTo {
                    controlX1: 241.40901454
                    controlY1: -231.60508730
                    controlX2: 241.34566629
                    controlY2: -231.45564780
                    x: 241.27723216
                    y: -231.30720830
                },
                CubicCurveTo {
                    controlX1: 241.26918487
                    controlY1: -231.29058308
                    controlX2: 241.26010753
                    controlY2: -231.27202033
                    x: 241.25206025
                    y: -231.25545760
                },
                CubicCurveTo {
                    controlX1: 241.17963466
                    controlY1: -231.10508058
                    controlX2: 241.10315324
                    controlY2: -230.95664109
                    x: 241.01971896
                    y: -230.81207665
                },
                CubicCurveTo {
                    controlX1: 240.72699083
                    controlY1: -230.30719486
                    controlX2: 240.36685862
                    controlY2: -229.83062596
                    x: 239.92528786
                    y: -229.40187019
                },
                CubicCurveTo {
                    controlX1: 238.66076929
                    controlY1: -228.17435370
                    controlX2: 236.98191199
                    controlY2: -227.49959463
                    x: 235.19541416
                    y: -227.49959463
                },
                ClosePath {},
            ] // elements
        }; // Path
    } // end path path4

    /** path path4619 */
    function path4619() : Path {
        Path {
            id: "path4619"
            opacity: 1.00000000
            fill: Color.rgb(0x00, 0x33, 0x99, 1.00000000)
            stroke: Color.rgb(0xff, 0xff, 0xff, 1.00000000)
            strokeWidth: 0.31982726
            strokeLineCap: StrokeLineCap.BUTT
            strokeLineJoin: StrokeLineJoin.MITER
            strokeMiterLimit: 4.00000000
            strokeDashArray: [  ]
            elements: [
                MoveTo {
                    x: 234.48758000
                    y: -227.54884000
                },
                CubicCurveTo {
                    controlX1: 232.85467000
                    controlY1: -227.72728000
                    controlX2: 231.31851000
                    controlY2: -228.49249000
                    x: 230.23624000
                    y: -229.66658000
                },
                CubicCurveTo {
                    controlX1: 228.81618000
                    controlY1: -231.20711000
                    controlX2: 228.23575000
                    controlY2: -233.31002000
                    x: 228.67370000
                    y: -235.32768000
                },
                CubicCurveTo {
                    controlX1: 228.87522000
                    controlY1: -236.25609000
                    controlX2: 229.28859000
                    controlY2: -237.14031000
                    x: 229.87820000
                    y: -237.90417000
                },
                CubicCurveTo {
                    controlX1: 229.99325000
                    controlY1: -238.05322000
                    controlX2: 230.26037000
                    controlY2: -238.34445000
                    x: 230.47179000
                    y: -238.55135000
                },
                CubicCurveTo {
                    controlX1: 231.73156000
                    controlY1: -239.78415000
                    controlX2: 233.41447000
                    controlY2: -240.46334000
                    x: 235.20940000
                    y: -240.46334000
                },
                CubicCurveTo {
                    controlX1: 237.29606000
                    controlY1: -240.46334000
                    controlX2: 239.25647000
                    controlY2: -239.51362000
                    x: 240.50850000
                    y: -237.89620000
                },
                CubicCurveTo {
                    controlX1: 242.54712000
                    controlY1: -235.26262000
                    controlX2: 242.23870000
                    controlY2: -231.58720000
                    x: 239.78800000
                    y: -229.30989000
                },
                CubicCurveTo {
                    controlX1: 238.81472000
                    controlY1: -228.40547000
                    controlX2: 237.66124000
                    controlY2: -227.84047000
                    x: 236.32072000
                    y: -227.61153000
                },
                CubicCurveTo {
                    controlX1: 235.86084000
                    controlY1: -227.53303000
                    controlX2: 234.92540000
                    controlY2: -227.50100000
                    x: 234.48758000
                    y: -227.54883000
                },
                LineTo {
                    x: 234.48758000
                    y: -227.54884000
                },
                ClosePath {},
            ] // elements
        }; // Path
    } // end path path4619

   override function create(): Node {
       Group {
           content: [
               path4(),
               path4619(),
           ] // content
           transforms: Translate { x : -203.31292324, y : 281.48435918 }
       } // Group
   } // function create()
} // class comet32


/*###################################################################
### E N D   C L A S S    comet32
###################################################################*/


